PRESETS = [
    {
        "kind": "bike",
        "name": "",
        "mass": 100,
        "speed": 25,
        "rolling_resistance": 2,
        "wheel_radius": 350,
        "drag_coefficient": 1.0,
        "frontal_area": 0.4,
        "inefficiency": 10,
        "regen_efficiency": 10,
        "battery_voltage": 48,
        "charger_efficiency": 85,
        "bms_losses": 5,
        "thermal_losses": 5,
    },{
        "kind": "car",
        "name": "",
        "mass": 1500,
        "speed": 60,
        "rolling_resistance": 2,
        "wheel_radius": 320,
        "drag_coefficient": 0.35,
        "frontal_area": 2.2,
        "inefficiency": 10,
        "regen_efficiency": 60,
        "battery_voltage": 400,
        "charger_efficiency": 85,
        "bms_losses": 5,
        "thermal_losses": 5,
    },{
        "kind": "scooter",
        "name": "",
        "mass": 85,
        "speed": 20,
        "rolling_resistance": 2.5,
        "wheel_radius": 200,
        "drag_coefficient": 1.1,
        "frontal_area": 0.3,
        "inefficiency": 10,
        "regen_efficiency": 5,
        "battery_voltage": 36,
        "charger_efficiency": 85,
        "bms_losses": 5,
        "thermal_losses": 5,
    },
]