export const PRESETS = [
  {
    "kind": "bike",
    "name": "Example bike",
    "mass_kg": 100,
    "speed_kmh": 28.8,
    "rolling_resistance_lever_mm": 2,
    "wheel_radius_mm": 350,
    "drag_coefficient_cx": 1,
    "frontal_area_m2": 0.4,
    "inefficiency_percent": 10,
    "regen_efficiency_percent": 0,
    "battery_voltage_v": 12,
    "charger_efficiency_percent": 88,
    "bms_losses_percent": 5,
    "thermal_losses_percent": 5,
  },
  {
    "kind": "bike",
    "name": "City E-Bike 250W",
    "mass_kg": 100,
    "speed_kmh": 25,
    "rolling_resistance_lever_mm": 2,
    "wheel_radius_mm": 340,
    "drag_coefficient_cx": 0.9,
    "frontal_area_m2": 0.45,
    "inefficiency_percent": 12,
    "regen_efficiency_percent": 5,
    "battery_voltage_v": 36,
    "charger_efficiency_percent": 88,
    "bms_losses_percent": 5,
    "thermal_losses_percent": 6,
  },
  {
    "kind": "bike",
    "name": "MTB E-Bike 500W",
    "mass_kg": 125,
    "speed_kmh": 30,
    "rolling_resistance_lever_mm": 2,
    "wheel_radius_mm": 355,
    "drag_coefficient_cx": 1.0,
    "frontal_area_m2": 0.5,
    "inefficiency_percent": 15,
    "regen_efficiency_percent": 8,
    "battery_voltage_v": 48,
    "charger_efficiency_percent": 90,
    "bms_losses_percent": 5,
    "thermal_losses_percent": 8,
  },
  {
    "kind": "bike",
    "name": "Speed E-Bike 1000W",
    "mass_kg": 140,
    "speed_kmh": 45,
    "rolling_resistance_lever_mm": 2,
    "wheel_radius_mm": 360,
    "drag_coefficient_cx": 0.95,
    "frontal_area_m2": 0.55,
    "inefficiency_percent": 18,
    "regen_efficiency_percent": 10,
    "battery_voltage_v": 52,
    "charger_efficiency_percent": 92,
    "bms_losses_percent": 6,
    "thermal_losses_percent": 10,
  },
  {
    "kind": "bike",
    "name": "Enduro E-MTB 750W",
    "mass_kg": 135,
    "speed_kmh": 25,
    "rolling_resistance_lever_mm": 2,
    "wheel_radius_mm": 355,
    "drag_coefficient_cx": 1.05,
    "frontal_area_m2": 0.52,
    "inefficiency_percent": 20,
    "regen_efficiency_percent": 12,
    "battery_voltage_v": 48,
    "charger_efficiency_percent": 88,
    "bms_losses_percent": 6,
    "thermal_losses_percent": 12,
  },
  {
    "kind": "bike",
    "name": "Fat Tire E-Bike 750W",
    "mass_kg": 150,
    "speed_kmh": 28,
    "rolling_resistance_lever_mm": 2,
    "wheel_radius_mm": 380,
    "drag_coefficient_cx": 1.1,
    "frontal_area_m2": 0.6,
    "inefficiency_percent": 22,
    "regen_efficiency_percent": 5,
    "battery_voltage_v": 48,
    "charger_efficiency_percent": 90,
    "bms_losses_percent": 6,
    "thermal_losses_percent": 12,
  },
]